API Token loaded successfully.
Traceback (most recent call last):
  File "/home/runner/work/Python-Actions.FindMind/Python-Actions.FindMind/FindMind-fetch_and_save_stock_data.py", line 663, in <module>
    main()
  File "/home/runner/work/Python-Actions.FindMind/Python-Actions.FindMind/FindMind-fetch_and_save_stock_data.py", line 583, in main
    download_google_sheet(sheet_url, csv_file)
  File "/home/runner/work/Python-Actions.FindMind/Python-Actions.FindMind/FindMind-fetch_and_save_stock_data.py", line 526, in download_google_sheet
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/requests/models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://doc-14-8c-sheets.googleusercontent.com/pub/54bogvaave6cua4cdnls17ksc4/u7gjgfnc4olm3mobrrs6resj2g/1756178145000/112527681702624495272/*/e@2PACX-1vSINLlSv4NcCszvA5XOPsuYCxZEk9_tBnhgLvyDkcG73QgFObITFtaZRQ492wlS53NPBlQi0AfPHMVh?gid=1407177187&single=true&output=csv
